"""
Base types and configuration for enterprise integration
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Any, Set, Union
from datetime import datetime
from abc import ABC, abstractmethod

from models.schemas import SchemaResponse

class IntegrationType(Enum):
    """Types of integrations supported"""
    DATABASE = "database"
    CLOUD_STORAGE = "cloud_storage"
    API_ENDPOINT = "api_endpoint"
    MESSAGE_QUEUE = "message_queue"
    FILE_TRANSFER = "file_transfer"
    BUSINESS_INTELLIGENCE = "business_intelligence"
    DATA_CATALOG = "data_catalog"
    WORKFLOW_ENGINE = "workflow_engine"
    NOTIFICATION = "notification"
    AUTHENTICATION = "authentication"

class AuthenticationType(Enum):
    """Types of authentication methods"""
    API_KEY = "api_key"
    BASIC_AUTH = "basic_auth"
    OAUTH1 = "oauth1"
    OAUTH2 = "oauth2"
    JWT_BEARER = "jwt_bearer"
    AWS_IAM = "aws_iam"
    AZURE_AD = "azure_ad"
    GOOGLE_SERVICE_ACCOUNT = "google_service_account"
    SSH_KEY = "ssh_key"
    TLS_CERTIFICATE = "tls_certificate"

class IntegrationStatus(Enum):
    """Integration status states"""
    ACTIVE = "active"
    INACTIVE = "inactive"
    ERROR = "error"
    TESTING = "testing"
    PENDING = "pending"
    DEPRECATED = "deprecated"

class JobStatus(Enum):
    """Data transfer job status"""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    SCHEDULED = "scheduled"

class EventType(Enum):
    """Integration event types"""
    CONNECTION_ESTABLISHED = "connection_established"
    CONNECTION_LOST = "connection_lost"
    DATA_RECEIVED = "data_received"
    DATA_SENT = "data_sent"
    ERROR_OCCURRED = "error_occurred"
    SCHEMA_CHANGED = "schema_changed"
    AUTHENTICATION_FAILED = "authentication_failed"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"

@dataclass
class IntegrationCredentials:
    """Credentials for integration authentication"""
    auth_type: AuthenticationType
    credentials: Dict[str, Any]
    expires_at: Optional[datetime] = None
    refresh_token: Optional[str] = None
    
    def is_expired(self) -> bool:
        """Check if credentials are expired"""
        if self.expires_at is None:
            return False
        return datetime.now() >= self.expires_at
    
    def needs_refresh(self, buffer_minutes: int = 5) -> bool:
        """Check if credentials need refresh within buffer time"""
        if self.expires_at is None:
            return False
        buffer_time = datetime.now() + timedelta(minutes=buffer_minutes)
        return buffer_time >= self.expires_at

@dataclass
class IntegrationConfig:
    """Configuration for an integration"""
    integration_id: str
    name: str
    integration_type: IntegrationType
    endpoint_url: str
    credentials: IntegrationCredentials
    settings: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: IntegrationStatus = IntegrationStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    last_tested: Optional[datetime] = None
    last_error: Optional[str] = None
    retry_count: int = 0
    max_retries: int = 3
    timeout_seconds: int = 30

@dataclass
class DataTransferJob:
    """Represents a data transfer job"""
    job_id: str
    source_integration_id: str
    target_integration_id: str
    schema_mapping: Dict[str, Any]
    schedule: Optional[str] = None  # Cron expression
    status: JobStatus = JobStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    last_run: Optional[datetime] = None
    next_run: Optional[datetime] = None
    error_message: Optional[str] = None
    transfer_stats: Dict[str, Any] = field(default_factory=dict)
    retry_count: int = 0
    max_retries: int = 3

@dataclass
class IntegrationEvent:
    """Event generated by integration"""
    event_id: str
    integration_id: str
    event_type: EventType
    timestamp: datetime
    data: Dict[str, Any]
    processed: bool = False
    error_message: Optional[str] = None

@dataclass
class ConnectionMetrics:
    """Metrics for integration connection"""
    total_requests: int = 0
    successful_requests: int = 0
    failed_requests: int = 0
    average_response_time: float = 0.0
    last_request_time: Optional[datetime] = None
    uptime_percentage: float = 100.0
    error_rate: float = 0.0

@dataclass
class IntegrationHealth:
    """Health status of an integration"""
    integration_id: str
    is_healthy: bool
    status_message: str
    last_check: datetime
    metrics: ConnectionMetrics
    issues: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)

class BaseIntegration(ABC):
    """Base class for all integrations"""
    
    def __init__(self, config: IntegrationConfig):
        self.config = config
        self.client = None
        self.is_connected = False
        self.metrics = ConnectionMetrics()
    
    @abstractmethod
    async def connect(self) -> bool:
        """Establish connection to the integration"""
        pass
    
    @abstractmethod
    async def disconnect(self):
        """Close connection to the integration"""
        pass
    
    @abstractmethod
    async def test_connection(self) -> Dict[str, Any]:
        """Test the integration connection"""
        pass
    
    @abstractmethod
    async def get_schema(self) -> Optional[SchemaResponse]:
        """Get schema information from the integration"""
        pass
    
    async def refresh_credentials(self) -> bool:
        """Refresh authentication credentials if needed"""
        return True
    
    async def get_health_status(self) -> IntegrationHealth:
        """Get health status of the integration"""
        try:
            test_result = await self.test_connection()
            is_healthy = test_result.get("success", False)
            status_message = test_result.get("message", "Unknown status")
            
            return IntegrationHealth(
                integration_id=self.config.integration_id,
                is_healthy=is_healthy,
                status_message=status_message,
                last_check=datetime.now(),
                metrics=self.metrics
            )
        except Exception as e:
            return IntegrationHealth(
                integration_id=self.config.integration_id,
                is_healthy=False,
                status_message=f"Health check failed: {str(e)}",
                last_check=datetime.now(),
                metrics=self.metrics,
                issues=[str(e)]
            )
    
    def update_metrics(self, success: bool, response_time: float):
        """Update connection metrics"""
        self.metrics.total_requests += 1
        self.metrics.last_request_time = datetime.now()
        
        if success:
            self.metrics.successful_requests += 1
        else:
            self.metrics.failed_requests += 1
        
        # Update average response time
        total_time = self.metrics.average_response_time * (self.metrics.total_requests - 1)
        self.metrics.average_response_time = (total_time + response_time) / self.metrics.total_requests
        
        # Update error rate
        self.metrics.error_rate = (self.metrics.failed_requests / self.metrics.total_requests) * 100

def validate_integration_config(config: IntegrationConfig) -> List[str]:
    """Validate integration configuration"""
    issues = []
    
    if not config.integration_id:
        issues.append("Integration ID is required")
    
    if not config.name:
        issues.append("Integration name is required")
    
    if not config.endpoint_url:
        issues.append("Endpoint URL is required")
    
    if not config.credentials:
        issues.append("Credentials are required")
    
    # Validate URL format
    try:
        from urllib.parse import urlparse
        parsed = urlparse(config.endpoint_url)
        if not parsed.scheme or not parsed.netloc:
            issues.append("Invalid endpoint URL format")
    except:
        issues.append("Invalid endpoint URL")
    
    # Validate credentials based on auth type
    if config.credentials:
        auth_type = config.credentials.auth_type
        creds = config.credentials.credentials
        
        if auth_type == AuthenticationType.API_KEY and not creds.get("api_key"):
            issues.append("API key is required for API key authentication")
        
        elif auth_type == AuthenticationType.BASIC_AUTH:
            if not creds.get("username") or not creds.get("password"):
                issues.append("Username and password are required for basic authentication")
        
        elif auth_type == AuthenticationType.OAUTH2:
            required_fields = ["client_id", "client_secret"]
            for field in required_fields:
                if not creds.get(field):
                    issues.append(f"{field} is required for OAuth2 authentication")
    
    return issues

def create_integration_factory() -> Dict[IntegrationType, type]:
    """Factory function to create integration instances"""
    # This would be populated with actual integration classes
    return {
        IntegrationType.DATABASE: BaseIntegration,
        IntegrationType.CLOUD_STORAGE: BaseIntegration,
        IntegrationType.API_ENDPOINT: BaseIntegration,
        # Add other integration types as they are implemented
    }
