"""
Spark code generation
"""
import logging
from typing import Dict, List, Any, Optional
from datetime import datetime

from .base import (
    CodeFramework, GeneratedCode, ETLPipeline, DataSource,
    DataTransformation, DataDestination
)

logger = logging.getLogger(__name__)

class SparkCodeGenerator:
    """Generates PySpark code from ETL pipeline definitions"""
    
    def __init__(self):
        self.spark_version = "3.4.0"
    
    def generate_spark_job(self, pipeline: ETLPipeline, options: Dict[str, Any] = None) -> GeneratedCode:
        """Generate PySpark job from pipeline definition"""
        options = options or {}
        
        try:
            # Generate main Spark code
            spark_code = self._generate_spark_code(pipeline, options)
            
            # Generate configuration files
            config_files = self._generate_config_files(pipeline, options)
            
            # Generate requirements
            requirements = self._generate_requirements(pipeline, options)
            
            # Generate Docker configuration
            docker_config = self._generate_docker_config(pipeline, options)
            
            # Generate deployment scripts
            deployment_scripts = self._generate_deployment_scripts(pipeline, options)
            
            return GeneratedCode(
                framework=CodeFramework.SPARK,
                main_code=spark_code,
                config_files=config_files,
                requirements=requirements,
                docker_config=docker_config,
                deployment_scripts=deployment_scripts,
                metadata={
                    "pipeline_id": pipeline.pipeline_id,
                    "generated_at": datetime.now().isoformat(),
                    "spark_version": self.spark_version
                }
            )
            
        except Exception as e:
            logger.error(f"Failed to generate Spark job: {str(e)}")
            raise
    
    def _generate_spark_code(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> str:
        """Generate the main PySpark code"""
        
        # Generate imports
        imports = self._generate_imports(pipeline)
        
        # Generate Spark session initialization
        spark_init = self._generate_spark_initialization(pipeline, options)
        
        # Generate extraction logic
        extraction_code = self._generate_extraction_code(pipeline)
        
        # Generate transformation logic
        transformation_code = self._generate_transformation_code(pipeline)
        
        # Generate loading logic
        loading_code = self._generate_loading_code(pipeline)
        
        # Generate main function
        main_function = self._generate_main_function(pipeline)
        
        # Combine all parts
        spark_code_parts = [
            imports,
            "",
            spark_init,
            "",
            extraction_code,
            "",
            transformation_code,
            "",
            loading_code,
            "",
            main_function
        ]
        
        return "\n".join(spark_code_parts)
    
    def _generate_imports(self, pipeline: ETLPipeline) -> str:
        """Generate import statements"""
        imports = [
            "#!/usr/bin/env python3",
            "\"\"\"",
            f"Spark ETL Pipeline: {pipeline.name}",
            f"Generated by SchemaSage",
            f"Description: {pipeline.description}",
            "\"\"\"",
            "",
            "import sys",
            "import logging",
            "from typing import Dict, Any, Optional",
            "from pyspark.sql import SparkSession, DataFrame",
            "from pyspark.sql.functions import *",
            "from pyspark.sql.types import *",
            "import argparse",
            "import json"
        ]
        
        # Add specific imports based on sources and destinations
        source_types = {source.source_type for source in pipeline.sources}
        dest_types = {dest.destination_type for dest in pipeline.destinations}
        
        if any(t in ["postgres", "mysql", "oracle"] for t in source_types | dest_types):
            imports.append("from pyspark.sql import DataFrameWriter")
        
        if any(t in ["s3", "aws"] for t in source_types | dest_types):
            imports.append("import boto3")
        
        if any(t in ["kafka"] for t in source_types | dest_types):
            imports.append("from pyspark.sql.streaming import *")
        
        return "\n".join(imports)
    
    def _generate_spark_initialization(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> str:
        """Generate Spark session initialization"""
        
        app_name = f"{pipeline.pipeline_id}_{pipeline.name.replace(' ', '_')}"
        
        spark_init = f'''
def create_spark_session(app_name: str = "{app_name}") -> SparkSession:
    """Create and configure Spark session"""
    
    builder = SparkSession.builder \\
        .appName(app_name) \\
        .config("spark.sql.adaptive.enabled", "true") \\
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true")
    
    # Add configuration based on sources and destinations
'''
        
        # Add JDBC configurations for database sources
        for source in pipeline.sources:
            if source.source_type in ["postgres", "mysql", "oracle"]:
                spark_init += f'''
    # {source.source_type.title()} JDBC configuration
    builder = builder.config("spark.jars.packages", "org.postgresql:postgresql:42.5.0")
'''
        
        # Add S3 configuration if needed
        if any(s.source_type in ["s3", "aws"] for s in pipeline.sources) or \
           any(d.destination_type in ["s3", "aws"] for d in pipeline.destinations):
            spark_init += '''
    # AWS S3 configuration
    builder = builder.config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \\
                    .config("spark.hadoop.fs.s3a.aws.credentials.provider", 
                           "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider")
'''
        
        spark_init += '''
    
    spark = builder.getOrCreate()
    spark.sparkContext.setLogLevel("WARN")
    
    return spark
'''
        
        return spark_init.strip()
    
    def _generate_extraction_code(self, pipeline: ETLPipeline) -> str:
        """Generate data extraction functions"""
        
        extraction_functions = []
        
        for i, source in enumerate(pipeline.sources):
            function_name = f"extract_from_{source.source_type}_{i+1}"
            
            if source.source_type in ["postgres", "mysql", "oracle"]:
                extraction_function = self._generate_database_extraction(function_name, source)
            elif source.source_type == "csv":
                extraction_function = self._generate_csv_extraction(function_name, source)
            elif source.source_type == "json":
                extraction_function = self._generate_json_extraction(function_name, source)
            elif source.source_type == "parquet":
                extraction_function = self._generate_parquet_extraction(function_name, source)
            elif source.source_type in ["s3", "aws"]:
                extraction_function = self._generate_s3_extraction(function_name, source)
            else:
                extraction_function = self._generate_generic_extraction(function_name, source)
            
            extraction_functions.append(extraction_function)
        
        return "\n\n".join(extraction_functions)
    
    def _generate_database_extraction(self, function_name: str, source: DataSource) -> str:
        """Generate database extraction function"""
        
        config = source.connection_config
        
        return f'''
def {function_name}(spark: SparkSession) -> DataFrame:
    """Extract data from {source.source_type} database"""
    
    try:
        # Database configuration
        jdbc_url = "{config.get('jdbc_url', 'jdbc:postgresql://localhost:5432/db')}"
        table_name = "{config.get('table_name', 'table')}"
        user = "{config.get('username', 'user')}"
        password = "{config.get('password', 'password')}"
        
        # Read from database
        df = spark.read.format("jdbc") \\
            .option("url", jdbc_url) \\
            .option("dbtable", table_name) \\
            .option("user", user) \\
            .option("password", password) \\
            .option("driver", "org.postgresql.Driver") \\
            .load()
        
        # Apply any filters or optimizations
        query = "{config.get('query', '')}"
        if query:
            df = spark.read.format("jdbc") \\
                .option("url", jdbc_url) \\
                .option("query", query) \\
                .option("user", user) \\
                .option("password", password) \\
                .load()
        
        # Cache if specified
        if {config.get('cache', False)}:
            df = df.cache()
        
        logging.info(f"Extracted {{df.count()}} rows from {source.source_type}")
        return df
        
    except Exception as e:
        logging.error(f"Error extracting from {source.source_type}: {{str(e)}}")
        raise
'''
    
    def _generate_csv_extraction(self, function_name: str, source: DataSource) -> str:
        """Generate CSV extraction function"""
        
        config = source.connection_config
        
        return f'''
def {function_name}(spark: SparkSession) -> DataFrame:
    """Extract data from CSV file"""
    
    try:
        file_path = "{config.get('file_path', 'input.csv')}"
        header = {config.get('header', True)}
        separator = "{config.get('separator', ',')}"
        
        df = spark.read.format("csv") \\
            .option("header", header) \\
            .option("sep", separator) \\
            .option("inferSchema", "true") \\
            .load(file_path)
        
        logging.info(f"Extracted {{df.count()}} rows from CSV: {{file_path}}")
        return df
        
    except Exception as e:
        logging.error(f"Error extracting from CSV: {{str(e)}}")
        raise
'''
    
    def _generate_s3_extraction(self, function_name: str, source: DataSource) -> str:
        """Generate S3 extraction function"""
        
        config = source.connection_config
        
        return f'''
def {function_name}(spark: SparkSession) -> DataFrame:
    """Extract data from S3"""
    
    try:
        bucket = "{config.get('bucket', 'default-bucket')}"
        key = "{config.get('key', 'data/')}"
        file_format = "{config.get('format', 'parquet')}"
        
        s3_path = f"s3a://{{bucket}}/{{key}}"
        
        if file_format == "parquet":
            df = spark.read.parquet(s3_path)
        elif file_format == "csv":
            df = spark.read.format("csv") \\
                .option("header", "true") \\
                .option("inferSchema", "true") \\
                .load(s3_path)
        elif file_format == "json":
            df = spark.read.json(s3_path)
        else:
            df = spark.read.load(s3_path)
        
        logging.info(f"Extracted {{df.count()}} rows from S3: {{s3_path}}")
        return df
        
    except Exception as e:
        logging.error(f"Error extracting from S3: {{str(e)}}")
        raise
'''
    
    def _generate_generic_extraction(self, function_name: str, source: DataSource) -> str:
        """Generate generic extraction function"""
        
        return f'''
def {function_name}(spark: SparkSession) -> DataFrame:
    """Extract data from {source.source_type}"""
    
    try:
        # Generic extraction logic
        config = {source.connection_config}
        
        # Implement extraction logic based on source type
        # This is a placeholder that should be customized
        df = spark.createDataFrame([(1, "sample", "data")], ["id", "col1", "col2"])
        
        logging.info(f"Extracted data from {source.source_type}")
        return df
        
    except Exception as e:
        logging.error(f"Error extracting from {source.source_type}: {{str(e)}}")
        raise
'''
    
    def _generate_transformation_code(self, pipeline: ETLPipeline) -> str:
        """Generate transformation functions"""
        
        if not pipeline.transformations:
            return "# No transformations defined"
        
        transformation_functions = []
        
        for i, transform in enumerate(pipeline.transformations):
            function_name = f"transform_{transform.operation}_{i+1}"
            
            if transform.operation == "filter":
                transform_func = self._generate_filter_transformation(function_name, transform)
            elif transform.operation == "select":
                transform_func = self._generate_select_transformation(function_name, transform)
            elif transform.operation == "aggregate":
                transform_func = self._generate_aggregate_transformation(function_name, transform)
            elif transform.operation == "join":
                transform_func = self._generate_join_transformation(function_name, transform)
            else:
                transform_func = self._generate_generic_transformation(function_name, transform)
            
            transformation_functions.append(transform_func)
        
        return "\n\n".join(transformation_functions)
    
    def _generate_filter_transformation(self, function_name: str, transform: DataTransformation) -> str:
        """Generate filter transformation"""
        
        params = transform.parameters or {}
        condition = params.get('condition', 'True')
        
        return f'''
def {function_name}(df: DataFrame) -> DataFrame:
    """Apply filter transformation"""
    
    try:
        condition = "{condition}"
        filtered_df = df.filter(condition)
        
        logging.info(f"Filter applied: {{condition}}, rows: {{filtered_df.count()}}")
        return filtered_df
        
    except Exception as e:
        logging.error(f"Error in filter transformation: {{str(e)}}")
        raise
'''
    
    def _generate_select_transformation(self, function_name: str, transform: DataTransformation) -> str:
        """Generate select transformation"""
        
        params = transform.parameters or {}
        columns = params.get('columns', [])
        
        return f'''
def {function_name}(df: DataFrame) -> DataFrame:
    """Apply select transformation"""
    
    try:
        columns = {columns}
        
        if columns:
            selected_df = df.select(*columns)
        else:
            selected_df = df  # No selection, return original
        
        logging.info(f"Selected columns: {{columns}}")
        return selected_df
        
    except Exception as e:
        logging.error(f"Error in select transformation: {{str(e)}}")
        raise
'''
    
    def _generate_aggregate_transformation(self, function_name: str, transform: DataTransformation) -> str:
        """Generate aggregate transformation"""
        
        params = transform.parameters or {}
        group_by = params.get('group_by', [])
        functions = params.get('functions', {})
        
        return f'''
def {function_name}(df: DataFrame) -> DataFrame:
    """Apply aggregate transformation"""
    
    try:
        group_by_cols = {group_by}
        agg_functions = {functions}
        
        if group_by_cols:
            # Group by specified columns
            grouped_df = df.groupBy(*group_by_cols)
            
            # Apply aggregation functions
            agg_exprs = []
            for col_name, func in agg_functions.items():
                if func == "sum":
                    agg_exprs.append(sum(col_name).alias(f"{{col_name}}_sum"))
                elif func == "avg":
                    agg_exprs.append(avg(col_name).alias(f"{{col_name}}_avg"))
                elif func == "count":
                    agg_exprs.append(count(col_name).alias(f"{{col_name}}_count"))
                elif func == "max":
                    agg_exprs.append(max(col_name).alias(f"{{col_name}}_max"))
                elif func == "min":
                    agg_exprs.append(min(col_name).alias(f"{{col_name}}_min"))
            
            if agg_exprs:
                result_df = grouped_df.agg(*agg_exprs)
            else:
                result_df = grouped_df.count()
        else:
            # Global aggregation
            result_df = df.agg(*[count("*").alias("total_count")])
        
        logging.info(f"Aggregation applied with {{len(group_by_cols)}} grouping columns")
        return result_df
        
    except Exception as e:
        logging.error(f"Error in aggregate transformation: {{str(e)}}")
        raise
'''
    
    def _generate_join_transformation(self, function_name: str, transform: DataTransformation) -> str:
        """Generate join transformation"""
        
        params = transform.parameters or {}
        
        return f'''
def {function_name}(left_df: DataFrame, right_df: DataFrame) -> DataFrame:
    """Apply join transformation"""
    
    try:
        join_type = "{params.get('join_type', 'inner')}"
        join_keys = {params.get('join_keys', [])}
        
        if isinstance(join_keys, list) and len(join_keys) > 0:
            joined_df = left_df.join(right_df, join_keys, join_type)
        else:
            # If no keys specified, try to find common columns
            common_cols = set(left_df.columns) & set(right_df.columns)
            if common_cols:
                joined_df = left_df.join(right_df, list(common_cols), join_type)
            else:
                raise ValueError("No join keys specified and no common columns found")
        
        logging.info(f"Join completed: {{join_type}} join on {{join_keys}}")
        return joined_df
        
    except Exception as e:
        logging.error(f"Error in join transformation: {{str(e)}}")
        raise
'''
    
    def _generate_generic_transformation(self, function_name: str, transform: DataTransformation) -> str:
        """Generate generic transformation"""
        
        return f'''
def {function_name}(df: DataFrame) -> DataFrame:
    """Apply {transform.operation} transformation"""
    
    try:
        # Generic transformation logic
        params = {transform.parameters or {}}
        
        # Implement transformation logic based on operation type
        # This is a placeholder that should be customized
        result_df = df  # Pass through for now
        
        logging.info(f"Applied {transform.operation} transformation")
        return result_df
        
    except Exception as e:
        logging.error(f"Error in {transform.operation} transformation: {{str(e)}}")
        raise
'''
    
    def _generate_loading_code(self, pipeline: ETLPipeline) -> str:
        """Generate data loading functions"""
        
        loading_functions = []
        
        for i, dest in enumerate(pipeline.destinations):
            function_name = f"load_to_{dest.destination_type}_{i+1}"
            
            if dest.destination_type in ["postgres", "mysql", "oracle"]:
                loading_function = self._generate_database_loading(function_name, dest)
            elif dest.destination_type == "csv":
                loading_function = self._generate_csv_loading(function_name, dest)
            elif dest.destination_type == "parquet":
                loading_function = self._generate_parquet_loading(function_name, dest)
            elif dest.destination_type in ["s3", "aws"]:
                loading_function = self._generate_s3_loading(function_name, dest)
            else:
                loading_function = self._generate_generic_loading(function_name, dest)
            
            loading_functions.append(loading_function)
        
        return "\n\n".join(loading_functions)
    
    def _generate_database_loading(self, function_name: str, dest: DataDestination) -> str:
        """Generate database loading function"""
        
        config = dest.connection_config
        
        return f'''
def {function_name}(df: DataFrame):
    """Load data to {dest.destination_type} database"""
    
    try:
        # Database configuration
        jdbc_url = "{config.get('jdbc_url', 'jdbc:postgresql://localhost:5432/db')}"
        table_name = "{config.get('table_name', 'output_table')}"
        user = "{config.get('username', 'user')}"
        password = "{config.get('password', 'password')}"
        write_mode = "{dest.write_mode}"
        
        # Write to database
        df.write.format("jdbc") \\
            .option("url", jdbc_url) \\
            .option("dbtable", table_name) \\
            .option("user", user) \\
            .option("password", password) \\
            .option("driver", "org.postgresql.Driver") \\
            .mode(write_mode) \\
            .save()
        
        logging.info(f"Loaded {{df.count()}} rows to {dest.destination_type} table: {{table_name}}")
        
    except Exception as e:
        logging.error(f"Error loading to {dest.destination_type}: {{str(e)}}")
        raise
'''
    
    def _generate_s3_loading(self, function_name: str, dest: DataDestination) -> str:
        """Generate S3 loading function"""
        
        config = dest.connection_config
        
        return f'''
def {function_name}(df: DataFrame):
    """Load data to S3"""
    
    try:
        bucket = "{config.get('bucket', 'default-bucket')}"
        key = "{config.get('key', 'output/')}"
        file_format = "{config.get('format', 'parquet')}"
        write_mode = "{dest.write_mode}"
        
        s3_path = f"s3a://{{bucket}}/{{key}}"
        
        writer = df.write.mode(write_mode)
        
        if file_format == "parquet":
            writer.parquet(s3_path)
        elif file_format == "csv":
            writer.format("csv").option("header", "true").save(s3_path)
        elif file_format == "json":
            writer.json(s3_path)
        else:
            writer.save(s3_path)
        
        logging.info(f"Loaded data to S3: {{s3_path}} in {{file_format}} format")
        
    except Exception as e:
        logging.error(f"Error loading to S3: {{str(e)}}")
        raise
'''
    
    def _generate_generic_loading(self, function_name: str, dest: DataDestination) -> str:
        """Generate generic loading function"""
        
        return f'''
def {function_name}(df: DataFrame):
    """Load data to {dest.destination_type}"""
    
    try:
        # Generic loading logic
        config = {dest.connection_config}
        write_mode = "{dest.write_mode}"
        
        # Implement loading logic based on destination type
        # This is a placeholder that should be customized
        df.show(10)  # For now, just show the data
        
        logging.info(f"Loaded data to {dest.destination_type}")
        
    except Exception as e:
        logging.error(f"Error loading to {dest.destination_type}: {{str(e)}}")
        raise
'''
    
    def _generate_main_function(self, pipeline: ETLPipeline) -> str:
        """Generate main execution function"""
        
        # Get function names
        extract_functions = [f"extract_from_{source.source_type}_{i+1}" 
                           for i, source in enumerate(pipeline.sources)]
        
        transform_functions = [f"transform_{transform.operation}_{i+1}" 
                             for i, transform in enumerate(pipeline.transformations)]
        
        load_functions = [f"load_to_{dest.destination_type}_{i+1}" 
                        for i, dest in enumerate(pipeline.destinations)]
        
        main_function = f'''
def main():
    """Main ETL pipeline execution"""
    
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Parse command line arguments
    parser = argparse.ArgumentParser(description="{pipeline.description}")
    parser.add_argument("--config", help="Configuration file path")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode")
    args = parser.parse_args()
    
    try:
        # Create Spark session
        spark = create_spark_session()
        
        logging.info("Starting ETL pipeline: {pipeline.name}")
        
        # Extract phase
        extracted_data = []
'''
        
        # Add extraction calls
        for func_name in extract_functions:
            main_function += f'''
        logging.info("Extracting data using {func_name}")
        df_{func_name} = {func_name}(spark)
        extracted_data.append(df_{func_name})
'''
        
        # Add transformation calls
        if transform_functions:
            main_function += '''
        
        # Transform phase
        current_df = extracted_data[0] if extracted_data else None
        
        if current_df is None:
            raise ValueError("No data extracted")
'''
            
            for func_name in transform_functions:
                main_function += f'''
        logging.info("Applying transformation: {func_name}")
        current_df = {func_name}(current_df)
'''
        else:
            main_function += '''
        
        # No transformations - use extracted data directly
        current_df = extracted_data[0] if extracted_data else None
'''
        
        # Add loading calls
        main_function += '''
        
        # Load phase
        if not args.dry_run:
'''
        
        for func_name in load_functions:
            main_function += f'''
            logging.info("Loading data using {func_name}")
            {func_name}(current_df)
'''
        
        main_function += '''
        else:
            logging.info("Dry run mode - skipping data loading")
            current_df.show(10)
        
        logging.info("ETL pipeline completed successfully")
        
    except Exception as e:
        logging.error(f"ETL pipeline failed: {{str(e)}}")
        raise
    
    finally:
        # Clean up Spark session
        if 'spark' in locals():
            spark.stop()

if __name__ == "__main__":
    main()
'''
        
        return main_function.strip()
    
    def _generate_config_files(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> Dict[str, str]:
        """Generate configuration files"""
        config_files = {}
        
        # Generate Spark configuration
        spark_config = {
            "spark": {
                "app_name": f"{pipeline.pipeline_id}_{pipeline.name}",
                "master": "local[*]",
                "config": {
                    "spark.sql.adaptive.enabled": "true",
                    "spark.sql.adaptive.coalescePartitions.enabled": "true"
                }
            },
            "sources": [
                {
                    "type": source.source_type,
                    "config": source.connection_config
                }
                for source in pipeline.sources
            ],
            "destinations": [
                {
                    "type": dest.destination_type,
                    "config": dest.connection_config,
                    "write_mode": dest.write_mode
                }
                for dest in pipeline.destinations
            ]
        }
        
        config_files["spark_config.json"] = json.dumps(spark_config, indent=2)
        
        return config_files
    
    def _generate_requirements(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> List[str]:
        """Generate requirements for Spark job"""
        requirements = [
            f"pyspark>={self.spark_version}",
            "py4j>=0.10.9"
        ]
        
        # Add specific requirements based on sources and destinations
        source_types = {source.source_type for source in pipeline.sources}
        dest_types = {dest.destination_type for dest in pipeline.destinations}
        
        if any(t in ["postgres", "mysql"] for t in source_types | dest_types):
            requirements.extend([
                "psycopg2-binary>=2.9.0",
                "PyMySQL>=1.0.0"
            ])
        
        if any(t in ["s3", "aws"] for t in source_types | dest_types):
            requirements.extend([
                "boto3>=1.26.0",
                "botocore>=1.29.0"
            ])
        
        return sorted(set(requirements))
    
    def _generate_docker_config(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> str:
        """Generate Dockerfile for Spark job"""
        
        dockerfile = f'''
FROM openjdk:11-jre-slim

# Install Python
RUN apt-get update && \\
    apt-get install -y python3 python3-pip && \\
    ln -s /usr/bin/python3 /usr/bin/python && \\
    rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV SPARK_VERSION={self.spark_version}
ENV HADOOP_VERSION=3.3.4
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.5-src.zip

# Download and install Spark
RUN wget https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz && \\
    tar -xzf spark-$SPARK_VERSION-bin-hadoop3.tgz && \\
    mv spark-$SPARK_VERSION-bin-hadoop3 $SPARK_HOME && \\
    rm spark-$SPARK_VERSION-bin-hadoop3.tgz

# Copy requirements and install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy application code
COPY . /app
WORKDIR /app

# Set the default command
CMD ["python", "main.py"]
'''
        
        return dockerfile.strip()
    
    def _generate_deployment_scripts(self, pipeline: ETLPipeline, options: Dict[str, Any]) -> Dict[str, str]:
        """Generate deployment scripts for Spark"""
        scripts = {}
        
        # Spark submit script
        scripts["submit.sh"] = f'''
#!/bin/bash

# Submit Spark job: {pipeline.name}

SPARK_HOME=${{SPARK_HOME:-/opt/spark}}
APP_NAME="{pipeline.pipeline_id}"
MAIN_FILE="main.py"

# Spark configuration
DRIVER_MEMORY="${{DRIVER_MEMORY:-2g}}"
EXECUTOR_MEMORY="${{EXECUTOR_MEMORY:-2g}}"
EXECUTOR_CORES="${{EXECUTOR_CORES:-2}}"
NUM_EXECUTORS="${{NUM_EXECUTORS:-2}}"

# Submit the job
$SPARK_HOME/bin/spark-submit \\
    --name "$APP_NAME" \\
    --driver-memory $DRIVER_MEMORY \\
    --executor-memory $EXECUTOR_MEMORY \\
    --executor-cores $EXECUTOR_CORES \\
    --num-executors $NUM_EXECUTORS \\
    --conf spark.sql.adaptive.enabled=true \\
    --conf spark.sql.adaptive.coalescePartitions.enabled=true \\
    $MAIN_FILE "$@"
'''
        
        # Kubernetes deployment
        scripts["k8s-deployment.yaml"] = f'''
apiVersion: v1
kind: ConfigMap
metadata:
  name: {pipeline.pipeline_id}-config
data:
  spark_config.json: |
    {{
      "app_name": "{pipeline.pipeline_id}",
      "pipeline_name": "{pipeline.name}"
    }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {pipeline.pipeline_id}
spec:
  template:
    spec:
      containers:
      - name: spark-job
        image: {pipeline.pipeline_id}:latest
        command: ["python", "main.py"]
        env:
        - name: SPARK_HOME
          value: "/opt/spark"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: {pipeline.pipeline_id}-config
      restartPolicy: Never
  backoffLimit: 3
'''
        
        return scripts
